switched from colon to hash rocket in email mapping
besides being inconsistent with the earlier mapping in the same hash,
using the colon forces the “email” param into a symbol.
SubmissionWorker.perform however, is looking for a string, so this test
fails due to a missing email address:

SubmissionWorkerTest#test_responds_to_perform:
ArgumentError: An SMTP To address is required to send a message. Set
the message smtp_envelope_to, to, cc, or bcc address.

/Users/craig/.rvm/gems/ruby-2.2.1@engineering-app/gems/mail-2.6.3/lib/ma
il/check_delivery_params.rb:9:in `check_delivery_params'

/Users/craig/.rvm/gems/ruby-2.2.1@engineering-app/gems/mail-2.6.3/lib/ma
il/network/delivery_methods/test_mailer.rb:39:in `deliver!'

/Users/craig/.rvm/gems/ruby-2.2.1@engineering-app/gems/mail-2.6.3/lib/ma
il/message.rb:2141:in `do_delivery'

/Users/craig/.rvm/gems/ruby-2.2.1@engineering-app/gems/mail-2.6.3/lib/ma
il/message.rb:238:in `deliver'

/Users/craig/.rvm/gems/ruby-2.2.1@engineering-app/gems/mail-2.6.3/lib/ma
il/mail.rb:140:in `deliver'

/Users/craig/Sites/engineering-app/workers/submission_worker.rb:15:in
`perform'

/Users/craig/Sites/engineering-app/test/workers/submission_worker_test.r
b:15:in `test_responds_to_perform'